#docker configuration
DOCKER_VERSION: "20.10.12~3-0~ubuntu"
DOCKER_COMPOSE_VERSION: "v2.2.3"
DOCKER_PACKAGES:
- apt-transport-https
- ca-certificates
- curl
- gnupg
- lsb-release
- software-properties-common