---
- name: Mark Node with Label "{{ item }}"
  docker_node:
    hostname: "{{ item }}"
    labels:
      "{{ item }}": "1"
  with_items: "{{groups['{{ item | lower }}']}}"
  loop:
    - DATA_INFRA_NODE
    - ROUTER_NODE