---
- name: Mark Node with Label"
  vars:
    labels:
      - hostname: data_infra_node
        name: DATA_INFRA_NODE
        value: "1"
  - set_fact: {"{{ labels.name }}":"{{ labels.value }}"}
    with_items: "{{ labels }}"
  docker_node:
    hostname: "{{ labels.hostname }}"
    labels:
      "{{ labels.name }}": "{{ labels.value  }}"
  with_items: "{{ labels }}"