- name: Creating docker virtual network - internal 
  docker_network:
    name: internal
    state: present
    driver: overlay
    attachable: true
    ipam_config:
      - subnet: "{{ docker_swarm_ipam_internal_subnet }}"
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  tags:
    - docker:swarm:network

- name: Creating docker virtual network - edge 
  docker_network:
    name: edge
    state: present
    driver: overlay
    attachable: true
    ipam_config:
      - subnet: "{{ docker_swarm_ipam_edge_subnet }}"
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  tags:
    - docker:swarm:network