- name: Set Docker Network
  docker_network:
    name: internal
    state: present
    driver: overlay
    attachable: true
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  tags:
    - docker:swarm:network