- name: Set Docker Network
  docker_network:
    name: overlay
    state: present
    driver: overlay
    attachable: internal
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  tags:
    - docker:swarm:network