---
# commented as an issue found when executing on the second time. this needs to be fixed
#- name: disable network time synchronization
#  command: timedatectl set-ntp off
#  run_once: true

- name: Install the NTP daemon to synchronize the clocks to ms.
  apt: 
    name: ntp

- name: Make sure ntp is started, and is enabled on restart.
  service: 
    name: ntp
    state: started
    enabled: yes
