---
- hosts: servers
  become: true
  become_user: root
  vars:
    server_list: servers
  tasks:
    - name: Update apt repo and cache on all {{server_list}}
      include_tasks: ../roles/common/tasks/update.yml 

- hosts: servers
  become: true
  become_user: root
  tasks:
    - name: update server settings
      include_tasks: ../roles/common/tasks/main.yml 
