---
- hosts: servers
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on all Ubuntu VMs
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- hosts: servers
  become: true
  become_user: root
  tasks:
    - name: update server settings
      include_tasks: ../roles/common/tasks/main.yml 
