---
- hosts: servers
  become: true
  become_user: root
  vars:
    hosts: servers
  tasks:
    - name: Update apt repo and cache on all servers
      include_tasks: ../roles/common/tasks/update.yml 

- hosts: servers
  become: true
  become_user: root
  tasks:
    - name: update server settings
      include_tasks: ../roles/common/tasks/main.yml 
